(() => {
  const EDITOR_PASSWORD_HASH = '946d8f0d81ec485967e9ace51d111ef8f54738dd10be88a009f81e71f880689a'; // senha temporária: Doc24@Org2026
  const isEditorPage = document.body.dataset.mode === 'editor';
  const state = { data:null, currentCountry:'Brasil', selectedId:null, scale:.9, panX:30, panY:30, nodeDrag:null, canvasDrag:null, unlocked:!isEditorPage };
  const W=180,H=70;
  const $=id=>document.getElementById(id);
  const viewport=$('viewport'),world=$('world'),nodesEl=$('nodes'),svg=$('links'),panel=$('panel');

  async function sha256(text){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
  async function loadData(){const r=await fetch(`data.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Não foi possível carregar data.json');state.data=await r.json();state.currentCountry=Object.keys(state.data.countries)[0]||'Brasil';render();applyTransform();setTimeout(center,50)}
  function list(){return state.data.countries[state.currentCountry]||[]}function byId(id){return list().find(n=>n.id===id)}
  function applyTransform(){world.style.transform=`translate(${state.panX}px,${state.panY}px) scale(${state.scale})`}
  function tabs(){const box=$('tabs');box.innerHTML='';Object.keys(state.data.countries).forEach(c=>{const b=document.createElement('button');b.className='tab'+(c===state.currentCountry?' active':'');b.textContent=c;b.onclick=()=>{state.currentCountry=c;state.selectedId=null;render();center()};box.appendChild(b)})}
  function badge(){return state.currentCountry==='México'?'MEX':state.currentCountry==='Argentina'?'ARG':'BRA'}
  function render(){if(!state.data)return;tabs();$('countryTitle').textContent=state.currentCountry;$('countryInfo').textContent=`${list().length} posições`;nodesEl.innerHTML='';for(const n of list()){const d=document.createElement('div');d.className=`node area-${n.area||'shared'}${state.selectedId===n.id?' selected':''}`;d.dataset.id=n.id;d.style.left=n.x+'px';d.style.top=n.y+'px';d.innerHTML=`<div class="mini"><span class="doc">DOC24</span><span class="badge">${badge()}</span></div><div class="role"></div><div class="name"></div>`;d.querySelector('.role').textContent=n.role;d.querySelector('.name').textContent=state.data.showNames&&n.name?`Nome: ${n.name}`:'';if(isEditorPage){d.addEventListener('mousedown',startNodeDrag);d.addEventListener('click',e=>{e.stopPropagation();state.selectedId=n.id;render();openPanel()})}nodesEl.appendChild(d)}drawLinks();if(isEditorPage&&state.selectedId)openPanel();else if(panel)panel.hidden=true}
  function svgPath(d){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('class','link');p.setAttribute('d',d);svg.appendChild(p)}
  function drawLinks(){svg.innerHTML='';const arr=list();let maxX=1800,maxY=1200;arr.forEach(n=>{maxX=Math.max(maxX,n.x+W+250);maxY=Math.max(maxY,n.y+H+250)});svg.setAttribute('width',maxX);svg.setAttribute('height',maxY);svg.style.width=maxX+'px';svg.style.height=maxY+'px';const groups=new Map();for(const n of arr){if(!n.parent)continue;if(!groups.has(n.parent))groups.set(n.parent,[]);groups.get(n.parent).push(n)}for(const [parentId,children] of groups){const p=byId(parentId);if(!p)continue;children.sort((a,b)=>a.x-b.x);const px=p.x+W/2,py=p.y+H;const tops=children.map(c=>c.y);const nearest=Math.min(...tops);let busY=Math.max(py+24,Math.min(nearest-24,py+(nearest-py)/2));if(children.length===1){const c=children[0],cx=c.x+W/2,cy=c.y;svgPath(`M ${px} ${py} V ${busY} H ${cx} V ${cy}`);continue}const xs=children.map(c=>c.x+W/2),minX=Math.min(...xs),maxX=Math.max(...xs);svgPath(`M ${px} ${py} V ${busY}`);svgPath(`M ${minX} ${busY} H ${maxX}`);for(const c of children){const cx=c.x+W/2,cy=c.y;svgPath(`M ${cx} ${busY} V ${cy}`)}}}
  function startNodeDrag(e){if(!isEditorPage||!state.unlocked)return;e.stopPropagation();const n=byId(e.currentTarget.dataset.id);state.nodeDrag={n,sx:e.clientX,sy:e.clientY,ox:n.x,oy:n.y}}
  window.addEventListener('mousemove',e=>{if(state.nodeDrag){const dx=(e.clientX-state.nodeDrag.sx)/state.scale,dy=(e.clientY-state.nodeDrag.sy)/state.scale;state.nodeDrag.n.x=Math.round(state.nodeDrag.ox+dx);state.nodeDrag.n.y=Math.round(state.nodeDrag.oy+dy);const el=nodesEl.querySelector(`[data-id="${state.nodeDrag.n.id}"]`);if(el){el.style.left=state.nodeDrag.n.x+'px';el.style.top=state.nodeDrag.n.y+'px'}drawLinks()}else if(state.canvasDrag){state.panX=e.clientX-state.canvasDrag.sx;state.panY=e.clientY-state.canvasDrag.sy;applyTransform()}})
  window.addEventListener('mouseup',()=>{state.nodeDrag=null;state.canvasDrag=null;viewport.classList.remove('grabbing')})
  viewport.addEventListener('mousedown',e=>{if(e.target.closest('.node')||e.button!==0)return;state.canvasDrag={sx:e.clientX-state.panX,sy:e.clientY-state.panY};viewport.classList.add('grabbing')})
  viewport.addEventListener('wheel',e=>{e.preventDefault();const r=viewport.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,wx=(mx-state.panX)/state.scale,wy=(my-state.panY)/state.scale;state.scale=Math.max(.25,Math.min(1.8,state.scale+(e.deltaY<0?.08:-.08)));state.panX=mx-wx*state.scale;state.panY=my-wy*state.scale;applyTransform()},{passive:false})
  function isDescendant(candidate,ancestor){let n=byId(candidate),guard=0;while(n&&n.parent&&guard++<200){if(n.parent===ancestor)return true;n=byId(n.parent)}return false}
  function openPanel(){const n=byId(state.selectedId);if(!n||!panel)return;if(document.activeElement&&['INPUT','SELECT'].includes(document.activeElement.tagName)&&panel.contains(document.activeElement))return;panel.hidden=false;$('roleInput').value=n.role;$('nameInput').value=n.name||'';$('areaSelect').value=n.area||'shared';$('parentSelect').innerHTML='<option value="">Sem gestor / raiz</option>';list().filter(x=>x.id!==n.id&&!isDescendant(x.id,n.id)).forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.role+(x.name?` — ${x.name}`:'');$('parentSelect').appendChild(o)});$('parentSelect').value=n.parent||''}
  function bindEditor(){if(!isEditorPage)return;$('roleInput').oninput=()=>{const n=byId(state.selectedId);if(n){n.role=$('roleInput').value;updateSelectedCard(n)}};$('nameInput').oninput=()=>{const n=byId(state.selectedId);if(n){n.name=$('nameInput').value;updateSelectedCard(n)}};$('areaSelect').onchange=()=>{const n=byId(state.selectedId);if(n){n.area=$('areaSelect').value;render()}};$('parentSelect').onchange=()=>{const n=byId(state.selectedId);if(n){n.parent=$('parentSelect').value||null;drawLinks()}};$('addRootBtn').onclick=()=>addNode(null);$('addChildBtn').onclick=()=>addNode(state.selectedId);$('deleteBtn').onclick=deleteNode;$('namesBtn').onclick=()=>{state.data.showNames=!state.data.showNames;render()};$('organizeBtn').onclick=autoLayout;$('saveBtn').onclick=saveData;$('loginBtn').onclick=unlock;$('passwordInput').addEventListener('keydown',e=>{if(e.key==='Enter')unlock()})}
  function updateSelectedCard(n){const el=nodesEl.querySelector(`[data-id="${n.id}"]`);if(!el)return;el.querySelector('.role').textContent=n.role;el.querySelector('.name').textContent=state.data.showNames&&n.name?`Nome: ${n.name}`:''}
  function addNode(parent=null){const p=parent?byId(parent):null;const id='n_'+Date.now();list().push({id,role:'Novo cargo',name:'',parent:parent||null,area:p?.area||'shared',x:p?p.x:600,y:p?p.y+145:260});state.selectedId=id;render();openPanel()}
  function deleteNode(){if(!state.selectedId)return;const id=state.selectedId;state.data.countries[state.currentCountry]=list().filter(n=>n.id!==id).map(n=>n.parent===id?{...n,parent:null}:n);state.selectedId=null;render()}
  function subtreeWidth(n,children,memo){if(memo.has(n.id))return memo.get(n.id);const ch=children.get(n.id)||[];const width=ch.length?Math.max(W,ch.reduce((sum,c)=>sum+subtreeWidth(c,children,memo),0)+(ch.length-1)*34):W;memo.set(n.id,width);return width}
  function autoLayout(){const arr=list(),children=new Map();arr.forEach(n=>children.set(n.id,[]));arr.forEach(n=>{if(n.parent&&children.has(n.parent))children.get(n.parent).push(n)});for(const ch of children.values())ch.sort((a,b)=>a.x-b.x);const roots=arr.filter(n=>!n.parent||!children.has(n.parent));const memo=new Map();let cursor=90;function place(n,depth,left){const width=subtreeWidth(n,children,memo),ch=children.get(n.id)||[];if(!ch.length)n.x=left+(width-W)/2;else{let cLeft=left;for(const c of ch){const cw=subtreeWidth(c,children,memo);place(c,depth+1,cLeft);cLeft+=cw+34}const first=ch[0],last=ch[ch.length-1];n.x=((first.x+W/2)+(last.x+W/2))/2-W/2}n.y=92+depth*145}for(const r of roots){const rw=subtreeWidth(r,children,memo);place(r,0,cursor);cursor+=rw+80}render();center()}
  function center(){const arr=list();if(!arr.length)return;const minX=Math.min(...arr.map(n=>n.x)),maxX=Math.max(...arr.map(n=>n.x+W)),minY=Math.min(...arr.map(n=>n.y)),maxY=Math.max(...arr.map(n=>n.y+H));const vw=viewport.clientWidth,vh=viewport.clientHeight;state.scale=Math.max(.38,Math.min(1.08,(vw-80)/(maxX-minX+70),(vh-80)/(maxY-minY+70)));state.panX=(vw-(maxX-minX)*state.scale)/2-minX*state.scale;state.panY=(vh-(maxY-minY)*state.scale)/2-minY*state.scale;applyTransform()}
  function saveData(){const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  async function unlock(){const hash=await sha256($('passwordInput').value);if(hash===EDITOR_PASSWORD_HASH){state.unlocked=true;$('login').classList.add('hidden');document.body.classList.add('editor');loadData().catch(showLoadError)}else{$('loginError').textContent='Senha incorreta.'}}
  function showLoadError(err){console.error(err);$('countryTitle').textContent='Erro ao carregar';$('countryInfo').textContent='Verifique se data.json está na mesma pasta.'}
  $('centerBtn').onclick=center;$('zoomIn').onclick=()=>{state.scale=Math.min(1.8,state.scale+.1);applyTransform()};$('zoomOut').onclick=()=>{state.scale=Math.max(.25,state.scale-.1);applyTransform()};bindEditor();if(!isEditorPage)loadData().catch(showLoadError);
})();
